# Generated by Django 2.2 on 2020-04-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-price']},
        ),
    ]
