# Generated by Django 2.2 on 2020-05-06 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_auto_20200429_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['post_date']},
        ),
        migrations.AddField(
            model_name='advertisment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
