# Generated by Django 2.2 on 2020-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_auto_20200506_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('CA', 'Carpenter'), ('PL', 'Plumber'), ('EL', 'Electrician'), ('AC', 'Installations & Repairs'), ('PA', 'Painters'), ('CL', 'Cleaning'), ('PT', 'Pest Control'), ('MC', 'Misc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
