# Generated by Django 2.2 on 2020-05-10 12:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_auto_20200510_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=stdimage.models.JPEGField(upload_to=''),
        ),
    ]
