# Generated by Django 2.2 on 2020-05-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_auto_20200510_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['-postdate']},
        ),
        migrations.RenameField(
            model_name='advertisment',
            old_name='post_date',
            new_name='postdate',
        ),
    ]
