# Generated by Django 2.2 on 2020-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_auto_20200510_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nameSlug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
