# Generated by Django 2.2 on 2020-02-23 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seller',
            new_name='is_employee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
