# Generated by Django 2.2 on 2020-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_handyman',
            field=models.BooleanField(default=False),
        ),
    ]
