# Generated by Django 2.2 on 2020-05-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_auto_20200519_1955'),
        ('accounts', '0006_auto_20200519_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='assignment_id',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='mapp.Assignment'),
            preserve_default=False,
        ),
    ]
